- id: '1543869771361'
  alias: Ligar luz do quarto ao pôr do sol
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - alias: ''
    data: {}
    service: light.turn_on
- id: '1544450074284'
  alias: Apagar luzes ao sair da zona de casa
  trigger:
  - entity_id: device_tracker.0036766429
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - service: light.turn_off
  - data: {}
    service: switch.turn_off
- id: '1544475460922'
  alias: Ligar o PC ao chegar em casa
  trigger:
  - entity_id: device_tracker.0036766429
    event: enter
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data:
      mac: 94:de:80:7f:85:79
    service: wake_on_lan.send_magic_packet
