- id: '1543869771361'
  alias: Ligar luz do quarto ao pôr do sol
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - alias: ''
    data: {}
    service: light.turn_on
- id: '1544450074284'
  alias: Apagar luzes ao sair da zona de casa
  trigger:
  - entity_id: device_tracker.0036766429
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - service: light.turn_off
  - data: {}
    service: switch.turn_off
