
# Este arquivo armazena a maior parte das configurações do Home Assistant, como integrações, dispositivos, etc.
# Está escrita em YAML, uma linguagem de marcação simplificada, semelhante ao XML.


# Informações sobre o acesso ao Home Assistant via web, foi utilizado um serviço de DNS gratuito,
# a fim de deixá-lo disponível na internet sem um IP fixo. Também foi utilizado uma ferramenta 
# para SSL, para garantir a segurança da conexão.
http:
  base_url: smahassio.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
# Essa senha é utilizada por algumas integrações, bem como pode ser usada para login, como é crítica,
# foi armazenada no arquivo 'secrets.yaml', o qual não foi comittado para o git.
  api_password: !secret api_password
# Por questão de segurança, o acesso de um IP que tentar logar mais de 5 vezes com uma senha incorreta,
# será bloqueado permanentemente (ou até ser desbloqueado manualmente)
  ip_ban_enabled: true
  login_attempts_threshold: 5

homeassistant:
  # Nome do local onde o Home Assistant está rodando
  name: Casa do Marco
  # Localização do endereço, usado para cálculo do nascer e pôr do sol
  latitude: -29.447146
  longitude: -51.986468
  # Elevação do local, a qual impacta na previsão do tempo e nascer/pôr do sol
  elevation: 95
  # Sistema de medidad utilizado
  unit_system: metric
  # Fuso Horário
  time_zone: America/Sao_Paulo
  # Arquivo de customização
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Lâmpadas
light:
  - platform: yeelight
    devices:
      192.168.1.101:
        name: Luminária do Quarto

# Interruptores SonOff
# Foi feita uma integração com o WebHooks do IFTTT, usando a plataforma 'command_line' do Hass.io,
# optamos por colocar os links de cada comando no arquivo secrets, pois em posse deles qualquer pessoa
# teria acesso a senha do IFTTT e a alguns comandos deste.
switch:
  - platform: command_line
    switches:
        livingroom:
            command_on: !secret ifttt_ligar_sala
            command_off: !secret ifttt_desligar_quarto
            friendly_name: Lâmpada da Sala
        bedroom:
            command_on: !secret ifttt_ligar_quarto
            command_off: !secret ifttt_desligar_quarto
            friendly_name: Lâmpada da Quarto (teto)

# Sensores
sensor:
  # Previsão do Tempo
  - platform: yr
  # Velocidade da conexão (medida de hora em hora)
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
  # Tempo de viagem fornecido pelo Waze
  - platform: waze_travel_time
    origin: -29.447146,-51.986468
    destination: -29.444921,-51.954886
    region: 'US'
  # Estimativa de preço pelo Uber
  - platform: uber
    start_latitude: -29.447146
    start_longitude: -51.986468
    end_latitude: -29.444921
    end_longitude: -51.954886
    server_token: !secret uber_token
  # Tempo de viagem fornecido pelo Google Maps
  - platform: google_travel_time
    api_key: !secret google_api
    origin: -29.447146,-51.986468
    destination: -29.444921,-51.954886

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Integração com o IFTTT, a senha do Webhooks é mantida no arquvio 'secrets.yaml'
ifttt: 
   key: !secret ifttt_key

# Configuração para o GPS Logger, a senha é mantido no arquivo 'secrets.yaml'   
device_tracker:
  - platform: gpslogger
    password: !secret gpslogger_password
    
# Configuração das zonas no mapa
zone:
  - name: univates
    latitude: -29.444921
    longitude: -51.954886
    radius: 250
    icon: mdi:school
  - name: home
    latitude: -29.447146
    longitude: -51.986468
    radius: 250
    icon: mdi:home

# Previsão do tempo detalhada, usando a API DarkSky    
weather:
  - platform: darksky
    api_key: !secret darksky_key

# Detalhes do nível de radiação UV, usando a API OpenUV    
openuv:
  api_key: !secret openuv_key
  binary_sensors:
    monitored_conditions:
      - uv_protection_window
  sensors:
    monitored_conditions:
      - current_ozone_level
      - current_uv_index
      - current_uv_level
      - max_uv_index

# TV da Sala (controle remoto)
media_player:
  - platform: braviatv
    host: 192.168.1.103

# Possibilita o uso do serviço WakeOnLan para automações, etc.
wake_on_lan:

# Ativa uma lista de compras, editável via voz ou texto
shopping_list:

# Include dos arquivos auxiliares
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
